version: "3.8"
services:
  db:
    image: postgres:13.1
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=go_crud
      - POSTGRES_PASSWORD=go_crud
      - POSTGRES_DB=go_crud
      - DATABASE_HOST=localhost

  adminer:
    image: adminer:4.7.8-standalone
    ports:
      - "8080:8080"

  server:
    container_name: go_crud_server
    build:
      context: ./server
      target: base
    command: air -c .air.toml
    volumes:
      - ./server:/app/go/base
    ports:
      - "8000:8000"
      - "2345:2345"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE

  client:
    container_name: go_crud_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    command: yarn start
    ports:
      - "3000:3000"
