version: "3.8"
services:
  db:
    image: postgres:13.1
    restart: always
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go-crud
      - DATABASE_HOST=localhost

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - "8080:8080"

  server:
    container_name: go-crud
    build:
      context: ./server
    volumes:
      - ./server:/go/src/app
    ports:
      - "8000:8000"
    tty: true