FROM golang:1.15 as builder

WORKDIR /go/src/app

RUN    groupadd -g 10001 myapp \
    && useradd -u 10001 -g myapp myapp

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/app

EXPOSE 8000

USER myapp

ENTRYPOINT ["/go/bin/app"]
CMD ["./go-crud"]